use sea_orm_migration::prelude::*;
use uuid::Uuid;

#[derive(DeriveMigrationName)]
pub struct Migration;

const UUID_NAMESPACE: Uuid = Uuid::from_bytes([
    0x6b, 0xa7, 0xb8, 0x10, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8,
]);

fn deterministic_uuid(name: &str) -> Uuid {
    Uuid::new_v5(&UUID_NAMESPACE, name.as_bytes())
}

const DEGREES: &[&str] = &[
    "Administracja",
    "Administracja publiczna",
    "Aktorstwo",
    "Analityka biznesowa",
    "Analityka gospodarcza",
    "Analiza danych",
    "Anglistyka",
    "Animacja kultury",
    "Architektura",
    "Architektura krajobrazu",
    "Architektura wnętrz",
    "Archeologia",
    "Astronomia",
    "Automatyka i robotyka",
    "Bezpieczeństwo narodowe",
    "Bezpieczeństwo wewnętrzne",
    "Bibliotekoznawstwo",
    "Biochemia",
    "Biofizyka",
    "Bioinformatyka",
    "Biologia",
    "Biologia medyczna",
    "Biotechnologia",
    "Budowa maszyn",
    "Budownictwo",
    "Chemia",
    "Chemia medyczna",
    "Chemia techniczna",
    "Chirurgia",
    "Cyberbezpieczeństwo",
    "Dietetyka",
    "Dyplomacja",
    "Dziennikarstwo",
    "Dziennikarstwo i komunikacja społeczna",
    "Edukacja artystyczna",
    "Edukacja przedszkolna i wczesnoszkolna",
    "Edukacja techniczno-informatyczna",
    "Ekonometria",
    "Ekonomia",
    "Elektronika",
    "Elektronika i telekomunikacja",
    "Elektrotechnika",
    "Energetyka",
    "Etnologia",
    "Europeistyka",
    "Farmacja",
    "Filologia angielska",
    "Filologia francuska",
    "Filologia germańska",
    "Filologia hiszpańska",
    "Filologia klasyczna",
    "Filologia polska",
    "Filologia romańska",
    "Filologia rosyjska",
    "Filologia włoska",
    "Filozofia",
    "Finanse i rachunkowość",
    "Fizjoterapia",
    "Fizyka",
    "Fizyka medyczna",
    "Fizyka techniczna",
    "Fotografia",
    "Geodezja i kartografia",
    "Geografia",
    "Geologia",
    "Geoinformatyka",
    "Gospodarka przestrzenna",
    "Grafika",
    "Grafika komputerowa",
    "Historia",
    "Historia sztuki",
    "Iberystyka",
    "Informatyka",
    "Informatyka i ekonometria",
    "Informatyka stosowana",
    "Instrumentalistyka",
    "Inżynieria biomedyczna",
    "Inżynieria chemiczna i procesowa",
    "Inżynieria danych",
    "Inżynieria i analiza danych",
    "Inżynieria jądrowa",
    "Inżynieria kosmiczna",
    "Inżynieria materiałowa",
    "Inżynieria mechaniczna",
    "Inżynieria środowiska",
    "Inżynieria zarządzania",
    "Italianistyka",
    "Japonistyka",
    "Język chiński",
    "Kognitywistyka",
    "Komunikacja społeczna",
    "Konserwacja i restauracja dzieł sztuki",
    "Kosmetologia",
    "Kryminalistyka",
    "Kryminologia",
    "Kulturoznawstwo",
    "Leśnictwo",
    "Lekarski",
    "Lekarsko-dentystyczny",
    "Lingwistyka",
    "Lingwistyka stosowana",
    "Logistyka",
    "Logopedia",
    "Lotnictwo i kosmonautyka",
    "Malarstwo",
    "Marketing",
    "Marketing i komunikacja rynkowa",
    "Matematyka",
    "Matematyka stosowana",
    "Mechanika i budowa maszyn",
    "Mechatronika",
    "Media cyfrowe",
    "Mediacja i negocjacje",
    "Medycyna",
    "Metalurgia",
    "Międzynarodowe stosunki gospodarcze",
    "Mikrobiologia",
    "Muzykologia",
    "Muzykoterapia",
    "Nanotechnologia",
    "Nauki o polityce",
    "Nauki o rodzinie",
    "Neurobiologia",
    "Oceanografia",
    "Ochrona dóbr kultury",
    "Ochrona środowiska",
    "Ogrodnictwo",
    "Optometria",
    "Optyka",
    "Organizacja produkcji filmowej i telewizyjnej",
    "Pedagogika",
    "Pedagogika przedszkolna",
    "Pedagogika specjalna",
    "Pielęgniarstwo",
    "Politologia",
    "Polityka społeczna",
    "Położnictwo",
    "Prawo",
    "Prawo kanoniczne",
    "Produkcja muzyczna",
    "Psychologia",
    "Ratownictwo medyczne",
    "Reżyseria",
    "Rolnictwo",
    "Romanistyka",
    "Rusycystyka",
    "Rzeźba",
    "Scenografia",
    "Skandynawistyka",
    "Socjologia",
    "Sport",
    "Stosunki międzynarodowe",
    "Sztuczna inteligencja",
    "Sztuka mediów",
    "Sztuki piękne",
    "Technologia chemiczna",
    "Technologia drewna",
    "Technologia żywności i żywienie człowieka",
    "Teleinformatyka",
    "Telekomunikacja",
    "Teologia",
    "Towaroznawstwo",
    "Transport",
    "Turystyka i rekreacja",
    "Urbanistyka",
    "Weterynaria",
    "Wiedza o teatrze",
    "Wokalistyka",
    "Wojskoznawstwo",
    "Wzornictwo",
    "Zarządzanie",
    "Zarządzanie i inżynieria produkcji",
    "Zarządzanie publiczne",
    "Zdrowie publiczne",
    "Zoologia",
    "Zootechnika",
    // English-language programs
    "Computer Science",
    "Data Science",
    "Artificial Intelligence",
    "International Business",
    "International Relations",
    "European Studies",
    "Finance and Accounting",
    "Management",
    "Psychology",
];

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        let db = m.get_connection();
        for name in DEGREES {
            let id = deterministic_uuid(&format!("degree:{name}"));
            let escaped = name.replace('\'', "''");
            db.execute_unprepared(&format!(
                "INSERT INTO degrees (id, name) VALUES ('{id}', '{escaped}') ON CONFLICT (name) DO NOTHING"
            ))
            .await?;
        }
        Ok(())
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        let db = m.get_connection();
        for name in DEGREES {
            let escaped = name.replace('\'', "''");
            db.execute_unprepared(&format!("DELETE FROM degrees WHERE name = '{escaped}'"))
                .await?;
        }
        Ok(())
    }
}
