use sea_orm_migration::prelude::*;
use uuid::Uuid;

#[derive(DeriveMigrationName)]
pub struct Migration;

const UUID_NAMESPACE: Uuid = Uuid::from_bytes([
    0x6b, 0xa7, 0xb8, 0x10, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8,
]);

fn deterministic_uuid(name: &str) -> Uuid {
    Uuid::new_v5(&UUID_NAMESPACE, name.as_bytes())
}

const DEGREES: &[&str] = &[
    "Administracja",
    "Adult Education and Developmental Activities Design",
    "African Studies",
    "American Studies",
    "Analityka biznesowa",
    "Antropozoologia \u{2013} mi\u{119}dzydziedzinowe studia przyrodniczo-spo\u{142}eczno-humanistyczne",
    "Applied Multilingual and Multicultural Studies",
    "Archaeology (Studies in English)",
    "Archeologia",
    "Architektura przestrzeni informacyjnych",
    "Artes Liberales",
    "Astronomia",
    "Bezpiecze\u{144}stwo wewn\u{119}trzne",
    "Bioetyka",
    "Biofizyka",
    "Bioinformatyka i biologia system\u{f3}w",
    "Biologia",
    "Biological Therapeutics",
    "Biotechnologia",
    "Business and Management",
    "Chemia",
    "Chemia j\u{105}drowa i radiofarmaceutyki",
    "Chemia medyczna",
    "Chemia stosowana",
    "Chemiczna analiza instrumentalna",
    "Cognitive Science",
    "Cyberbezpiecze\u{144}stwo",
    "Data Science and Business Analytics",
    "Digital Business",
    "Digital Marketing",
    "Doradztwo inwestycyjne",
    "Dziennikarstwo i medioznawstwo",
    "Edukacja alternatywna z animacj\u{105} spo\u{142}eczno-kulturaln\u{105}",
    "Edukacja alternatywna z edukacj\u{105} artystyczn\u{105}",
    "Ekonometria i Data Science",
    "Ekonomia",
    "Energetyka j\u{105}drowa",
    "Etnologia i antropologia kulturowa",
    "EU Energy and Climate Law",
    "European Environmental Economics and Policy",
    "European Politics and Economics",
    "Europeistyka",
    "Europeistyka-integracja europejska",
    "Europejskie studia optyki okularowej i optometrii",
    "Europejskie studia ukrainistyczne",
    "Fennistyka",
    "Filologia angielska",
    "Filologia angielska \u{2013} j\u{119}zykoznawstwo (English Studies \u{2013} Linguistics)",
    "Filologia angielska \u{2013} literatura i kultura (English Studies \u{2013} Literature and Culture)",
    "Filologia ba\u{142}tycka",
    "Filologia bia\u{142}oruska z j\u{119}zykiem angielskim",
    "Filologia iberyjska",
    "Filologia klasyczna i studia \u{15b}r\u{f3}dziemnomorskie",
    "Filologia nowogrecka",
    "Filologia polska",
    "Filologia polskiego j\u{119}zyka migowego",
    "Filologia roma\u{144}ska",
    "Filologia rosyjska",
    "Filologia w\u{142}oska",
    "Filozofia",
    "Finance, International Investment and Accounting",
    "Finanse biznesu i rachunkowo\u{15b}\u{107}",
    "Finanse cyfrowe",
    "Finanse i rachunkowo\u{15b}\u{107}",
    "Fizyka",
    "Geografia",
    "Geoinformatyka i geofizyka w geoin\u{17c}ynierii",
    "Geologia poszukiwawcza",
    "Geologia stosowana",
    "Germanistyka",
    "Global Environment and Development",
    "Global Management",
    "Gospodarka przestrzenna",
    "Graduate Programme in International Relations",
    "Graduate Programme in Political Science",
    "Graduate Programme in Teaching English to Young Learners",
    "Helwetologia \u{2013} studia szwajcarskie",
    "Hispanistyka stosowana",
    "Historia",
    "Historia i kultura \u{17b}yd\u{f3}w",
    "Historia kultury w dobie humanistyki cyfrowej",
    "Historia sztuki",
    "History of Ancient Mediterranean Civilizations",
    "Humanitarian Action",
    "Hungarystyka",
    "Iberystyka: hispanistyka",
    "Iberystyka: portugalistyka",
    "Informacja naukowa i bibliotekoznawstwo",
    "Informatyka",
    "Informatyka i ekonometria",
    "Interdisciplinary Studies on Social Change: Mediterranean and Other European Borderlands",
    "International Business Program",
    "International Economics",
    "International Finance",
    "International Legal Communication",
    "International Management and Intercultural Communication \u{2013} Global MBA",
    "International Studies in Philosophy",
    "Inwestycje i analiza danych",
    "In\u{17c}ynieria nanostruktur",
    "In\u{17c}ynieria obliczeniowa",
    "J\u{119}zyk i spo\u{142}ecze\u{144}stwo - interdyscyplinarne studia nad dyskursem",
    "Kierunek lekarski",
    "Kognitywistyka",
    "Komunikacja mi\u{119}dzykulturowa \u{2013} Azja i Afryka",
    "Kryminalistyka i nauki s\u{105}dowe w zakresie biologia i genetyka s\u{105}dowa",
    "Kryminalistyka i nauki s\u{105}dowe w zakresie chemia s\u{105}dowa",
    "Kryminalistyka i nauki s\u{105}dowe w zakresie kryminalistyka og\u{f3}lna",
    "Kryminologia",
    "Kulturoznawstwo - cywilizacja \u{15b}r\u{f3}dziemnomorska",
    "Kulturoznawstwo - wiedza o kulturze",
    "Kulturoznawstwo Europy \u{15a}rodkowo-Wschodniej",
    "Kultury \u{15a}r\u{f3}dziemnomorza",
    "Laboratorium praktyk tekstowych",
    "Language Science and Technology",
    "Lingwistyka stosowana",
    "Logistyka i administrowanie w mediach",
    "Logopedia og\u{f3}lna i kliniczna",
    "Machine Learning",
    "Master in Food Systems",
    "Matematyka",
    "Mi\u{119}dzykulturowe studia filologiczne",
    "Mi\u{119}dzywydzia\u{142}owe studia ochrony \u{15b}rodowiska",
    "Migration Studies and New Societies",
    "Muzykologia",
    "Nanoin\u{17c}ynieria",
    "Nauczanie fizyki",
    "Nauczanie j\u{119}zyk\u{f3}w obcych",
    "Ochrona przyrody",
    "Ochrona \u{15b}rodowiska",
    "Ochrona zwierz\u{105}t",
    "Optometria",
    "Optometria i optyka okularowa",
    "Organizowanie rynku pracy",
    "Oriental Studies \u{2013} Inner Asia: Mongolian and Tibetan Studies",
    "Orientalistyka \u{2013} afrykanistyka",
    "Orientalistyka \u{2013} arabistyka",
    "Orientalistyka \u{2013} egiptologia",
    "Orientalistyka \u{2013} hebraistyka",
    "Orientalistyka \u{2013} indologia",
    "Orientalistyka \u{2013} iranistyka",
    "Orientalistyka \u{2013} japonistyka",
    "Orientalistyka \u{2013} koreanistyka",
    "Orientalistyka \u{2013} kultura Wschodu Staro\u{17c}ytnego",
    "Orientalistyka \u{2013} mongolistyka i tybetologia",
    "Orientalistyka \u{2013} sinologia",
    "Orientalistyka \u{2013} turkologia",
    "Pedagogika",
    "Pedagogika nauczycielska",
    "Pedagogika przedszkolna i wczesnoszkolna",
    "Pedagogika specjalna",
    "Physics (Studies in English)",
    "Podatki w biznesie \u{2013} procesy i technologie",
    "Politologia",
    "Polityka kulturalna i zarz\u{105}dzanie w kulturze",
    "Polityka publiczna",
    "Polityka spo\u{142}eczna",
    "Prawo",
    "Prawo finansowe i skarbow\u{15b}\u{107}",
    "Profilaktyka spo\u{142}eczna i resocjalizacja",
    "Projektowanie rozwoju regionalnego i lokalnego",
    "Psychologia",
    "Publikowanie wsp\u{f3}\u{142}czesne",
    "P\u{142}e\u{107} i seksualno\u{15b}\u{107}",
    "Quantitative Finance",
    "Quantum Physics and Chemistry \u{2013} Individual Research Studies",
    "Rachunkowo\u{15b}\u{107} i controlling",
    "Radiogenomika",
    "Religions of Asia and Africa: Buddhism, Islam and Others",
    "Resocjalizacja",
    "Resocjalizacja i penitencjarystyka",
    "Samorz\u{105}d terytorialny i polityka regionalna",
    "Slawistyka",
    "Social and Public Policy",
    "Social Design: profilaktyka i projektowanie us\u{142}ug spo\u{142}ecznych",
    "Socjologia",
    "Socjologia cyfrowa",
    "Socjologia interwencji spo\u{142}ecznych",
    "Socjologia stosowana i antropologia spo\u{142}eczna",
    "Socjologia \u{17c}ycia publicznego",
    "Stosowana psychologia zwierz\u{105}t",
    "Stosunki mi\u{119}dzynarodowe",
    "Studia amerykanistyczne",
    "Studia euroazjatyckie",
    "Studia filologiczno - kulturoznawcze",
    "Studia kanadyjskie",
    "Studia mi\u{119}dzydziedzinowe MISH",
    "Studia mi\u{119}dzykierunkowe MISMaP",
    "Studia miejskie",
    "Studia nowogreckie",
    "Studia regionalne i lokalne",
    "Studia wschodnie",
    "Sustainable Development",
    "Sztuczna inteligencja i kognitywistyka",
    "Sztuka pisania",
    "Sztuki spo\u{142}eczne",
    "Ukrainistyka z j\u{119}zykiem angielskim",
    "Undergraduate Programme in International Relations",
    "Undergraduate Programme in Political Science",
    "Zarz\u{105}dzanie",
    "Zarz\u{105}dzanie Big Data",
    "Zarz\u{105}dzanie finansami i rachunkowo\u{15b}\u{107}",
    "Zarz\u{105}dzanie ryzykiem",
    "Zastosowania fizyki w biologii i medycynie",
];

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        let db = m.get_connection();

        // Clear all old degrees that aren't referenced by profiles
        db.execute_unprepared(
            "DELETE FROM degrees WHERE name NOT IN (SELECT DISTINCT program FROM profiles WHERE program IS NOT NULL)"
        ).await?;

        for name in DEGREES {
            let id = deterministic_uuid(&format!("degree:{name}"));
            let escaped = name.replace('\'', "''");
            db.execute_unprepared(&format!(
                "INSERT INTO degrees (id, name) VALUES ('{id}', '{escaped}') ON CONFLICT (name) DO NOTHING"
            ))
            .await?;
        }
        Ok(())
    }

    async fn down(&self, _m: &SchemaManager) -> Result<(), DbErr> {
        // No-op: previous migration still has old degrees
        Ok(())
    }
}
