services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: loco
      POSTGRES_DB: poziomki-backend_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
