// @generated by diesel — hand-written based on existing DB migrations.
// Run `diesel print-schema` against the dev DB to regenerate.

diesel::table! {
    auth_rate_limits (id) {
        id -> Uuid,
        rate_key -> Varchar,
        window_start -> Timestamptz,
        attempts -> Int4,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    degrees (id) {
        id -> Uuid,
        name -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    event_attendees (event_id, profile_id) {
        event_id -> Uuid,
        profile_id -> Uuid,
        status -> Varchar,
    }
}

diesel::table! {
    event_interactions (profile_id, event_id, kind) {
        profile_id -> Uuid,
        event_id -> Uuid,
        kind -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    event_tags (event_id, tag_id) {
        event_id -> Uuid,
        tag_id -> Uuid,
    }
}

diesel::table! {
    events (id) {
        id -> Uuid,
        title -> Varchar,
        description -> Nullable<Text>,
        cover_image -> Nullable<Varchar>,
        location -> Nullable<Varchar>,
        starts_at -> Timestamptz,
        ends_at -> Nullable<Timestamptz>,
        creator_id -> Uuid,
        conversation_id -> Nullable<Varchar>,
        latitude -> Nullable<Float8>,
        longitude -> Nullable<Float8>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    job_outbox (id) {
        id -> Uuid,
        topic -> Varchar,
        payload -> Jsonb,
        attempts -> Int4,
        max_attempts -> Int4,
        available_at -> Timestamptz,
        locked_at -> Nullable<Timestamptz>,
        processed_at -> Nullable<Timestamptz>,
        failed_at -> Nullable<Timestamptz>,
        last_error -> Nullable<Text>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    metrics_scalar_samples (ts, instance_id, chart, series) {
        ts -> Timestamptz,
        instance_id -> Text,
        chart -> Int2,
        series -> Int2,
        value -> Float4,
    }
}

diesel::table! {
    metrics_histogram_samples (ts, instance_id, chart, series, bucket) {
        ts -> Timestamptz,
        instance_id -> Text,
        chart -> Int2,
        series -> Int2,
        bucket -> Int2,
        count -> Int8,
    }
}

diesel::table! {
    matrix_dm_rooms (id) {
        id -> Uuid,
        user_low_pid -> Uuid,
        user_high_pid -> Uuid,
        room_id -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    otp_codes (id) {
        id -> Uuid,
        email -> Varchar,
        code -> Varchar,
        attempts -> Int2,
        expires_at -> Timestamptz,
        last_sent_at -> Timestamptz,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    profile_tags (profile_id, tag_id) {
        profile_id -> Uuid,
        tag_id -> Uuid,
    }
}

diesel::table! {
    profiles (id) {
        id -> Uuid,
        user_id -> Int4,
        name -> Varchar,
        bio -> Nullable<Text>,
        age -> Nullable<Int2>,
        profile_picture -> Nullable<Varchar>,
        images -> Nullable<Jsonb>,
        program -> Nullable<Varchar>,
        gradient_start -> Nullable<Varchar>,
        gradient_end -> Nullable<Varchar>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    sessions (id) {
        id -> Uuid,
        user_id -> Int4,
        token -> Varchar,
        ip_address -> Nullable<Varchar>,
        user_agent -> Nullable<Varchar>,
        expires_at -> Timestamptz,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    tags (id) {
        id -> Uuid,
        name -> Varchar,
        scope -> Varchar,
        category -> Nullable<Varchar>,
        emoji -> Nullable<Varchar>,
        parent_id -> Nullable<Uuid>,
        onboarding_order -> Nullable<Varchar>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    uploads (id) {
        id -> Uuid,
        filename -> Varchar,
        owner_id -> Nullable<Uuid>,
        context -> Varchar,
        context_id -> Nullable<Varchar>,
        mime_type -> Varchar,
        deleted -> Bool,
        thumbhash -> Nullable<Bytea>,
        has_variants -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    user_settings (id) {
        id -> Uuid,
        user_id -> Int4,
        theme -> Varchar,
        language -> Varchar,
        notifications_enabled -> Bool,
        privacy_show_age -> Bool,
        privacy_show_program -> Bool,
        privacy_discoverable -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    users (id) {
        id -> Int4,
        pid -> Uuid,
        email -> Varchar,
        password -> Varchar,
        api_key -> Varchar,
        name -> Varchar,
        reset_token -> Nullable<Varchar>,
        reset_sent_at -> Nullable<Timestamptz>,
        email_verification_token -> Nullable<Varchar>,
        email_verification_sent_at -> Nullable<Timestamptz>,
        email_verified_at -> Nullable<Timestamptz>,
        magic_link_token -> Nullable<Varchar>,
        magic_link_expiration -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(event_attendees -> events (event_id));
diesel::joinable!(event_attendees -> profiles (profile_id));
diesel::joinable!(event_interactions -> events (event_id));
diesel::joinable!(event_interactions -> profiles (profile_id));
diesel::joinable!(event_tags -> events (event_id));
diesel::joinable!(event_tags -> tags (tag_id));
diesel::joinable!(events -> profiles (creator_id));
diesel::joinable!(profile_tags -> profiles (profile_id));
diesel::joinable!(profile_tags -> tags (tag_id));
diesel::joinable!(profiles -> users (user_id));
diesel::joinable!(sessions -> users (user_id));
diesel::joinable!(user_settings -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    auth_rate_limits,
    degrees,
    event_attendees,
    event_interactions,
    event_tags,
    events,
    job_outbox,
    matrix_dm_rooms,
    metrics_histogram_samples,
    metrics_scalar_samples,
    otp_codes,
    profile_tags,
    profiles,
    sessions,
    tags,
    uploads,
    user_settings,
    users,
);
