// @generated by diesel — hand-written based on existing DB migrations.
// Run `diesel print-schema` against the dev DB to regenerate.

diesel::table! {
    conversations (id) {
        id -> Uuid,
        kind -> Varchar,
        title -> Nullable<Varchar>,
        event_id -> Nullable<Uuid>,
        user_low_id -> Nullable<Int4>,
        user_high_id -> Nullable<Int4>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    conversation_members (conversation_id, user_id) {
        conversation_id -> Uuid,
        user_id -> Int4,
        joined_at -> Timestamptz,
        last_read_message_id -> Nullable<Uuid>,
    }
}

diesel::table! {
    messages (id) {
        id -> Uuid,
        conversation_id -> Uuid,
        sender_id -> Int4,
        body -> Text,
        kind -> Varchar,
        attachment_upload_id -> Nullable<Uuid>,
        reply_to_id -> Nullable<Uuid>,
        client_id -> Nullable<Varchar>,
        edited_at -> Nullable<Timestamptz>,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        moderation_verdict -> Nullable<Text>,
        moderation_categories -> Array<Text>,
        moderation_scanned_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    chat_message_reveals (message_id, viewer_user_id) {
        message_id -> Uuid,
        viewer_user_id -> Int4,
        revealed_at -> Timestamptz,
    }
}

diesel::table! {
    chat_message_reports (message_id, reporter_user_id) {
        message_id -> Uuid,
        reporter_user_id -> Int4,
        reason -> Text,
        description -> Nullable<Text>,
        automoderation_verdict -> Nullable<Text>,
        automoderation_categories -> Array<Text>,
        status -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    message_reactions (id) {
        id -> Uuid,
        message_id -> Uuid,
        user_id -> Int4,
        emoji -> Varchar,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    push_subscriptions (id) {
        id -> Uuid,
        user_id -> Int4,
        device_id -> Varchar,
        ntfy_topic -> Varchar,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    auth_rate_limits (id) {
        id -> Uuid,
        rate_key -> Varchar,
        window_start -> Timestamptz,
        attempts -> Int4,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    degrees (id) {
        id -> Uuid,
        name -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    event_attendees (event_id, profile_id) {
        event_id -> Uuid,
        profile_id -> Uuid,
        status -> Varchar,
    }
}

diesel::table! {
    event_interactions (profile_id, event_id, kind) {
        profile_id -> Uuid,
        event_id -> Uuid,
        kind -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    event_tags (event_id, tag_id) {
        event_id -> Uuid,
        tag_id -> Uuid,
    }
}

diesel::table! {
    events (id) {
        id -> Uuid,
        title -> Varchar,
        description -> Nullable<Text>,
        cover_image -> Nullable<Varchar>,
        category -> Nullable<Varchar>,
        location -> Nullable<Varchar>,
        starts_at -> Timestamptz,
        ends_at -> Nullable<Timestamptz>,
        creator_id -> Uuid,
        conversation_id -> Nullable<Varchar>,
        latitude -> Nullable<Float8>,
        longitude -> Nullable<Float8>,
        max_attendees -> Nullable<Int4>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        requires_approval -> Bool,
    }
}

diesel::table! {
    job_outbox (id) {
        id -> Uuid,
        topic -> Varchar,
        payload -> Jsonb,
        attempts -> Int4,
        max_attempts -> Int4,
        available_at -> Timestamptz,
        locked_at -> Nullable<Timestamptz>,
        processed_at -> Nullable<Timestamptz>,
        failed_at -> Nullable<Timestamptz>,
        last_error -> Nullable<Text>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    otp_codes (id) {
        id -> Uuid,
        email -> Varchar,
        code -> Varchar,
        attempts -> Int2,
        expires_at -> Timestamptz,
        last_sent_at -> Timestamptz,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    profile_blocks (blocker_id, blocked_id) {
        blocker_id -> Uuid,
        blocked_id -> Uuid,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    profile_bookmarks (profile_id, target_profile_id) {
        profile_id -> Uuid,
        target_profile_id -> Uuid,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    profile_tags (profile_id, tag_id) {
        profile_id -> Uuid,
        tag_id -> Uuid,
    }
}

diesel::table! {
    reports (id) {
        id -> Uuid,
        reporter_id -> Uuid,
        target_type -> Varchar,
        target_id -> Uuid,
        reason -> Varchar,
        description -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    profiles (id) {
        id -> Uuid,
        user_id -> Int4,
        name -> Varchar,
        bio -> Nullable<Text>,
        profile_picture -> Nullable<Varchar>,
        images -> Nullable<Jsonb>,
        program -> Nullable<Varchar>,
        gradient_start -> Nullable<Varchar>,
        gradient_end -> Nullable<Varchar>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        xp -> Int4,
        streak_current -> Int4,
        streak_longest -> Int4,
        streak_last_active -> Nullable<Date>,
    }
}

diesel::table! {
    xp_scans (scanner_id, scanned_id, day) {
        scanner_id -> Uuid,
        scanned_id -> Uuid,
        day -> Date,
    }
}

diesel::table! {
    task_completions (profile_id, task_id, day) {
        profile_id -> Uuid,
        task_id -> Text,
        day -> Date,
    }
}

diesel::table! {
    user_audit_log (id) {
        id -> Uuid,
        user_pid -> Uuid,
        action -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    sessions (id) {
        id -> Uuid,
        user_id -> Int4,
        token -> Varchar,
        ip_address -> Nullable<Varchar>,
        user_agent -> Nullable<Varchar>,
        expires_at -> Timestamptz,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    tags (id) {
        id -> Uuid,
        name -> Varchar,
        scope -> Varchar,
        category -> Nullable<Varchar>,
        emoji -> Nullable<Varchar>,
        parent_id -> Nullable<Uuid>,
        onboarding_order -> Nullable<Varchar>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    uploads (id) {
        id -> Uuid,
        filename -> Varchar,
        owner_id -> Nullable<Uuid>,
        context -> Varchar,
        context_id -> Nullable<Varchar>,
        mime_type -> Varchar,
        deleted -> Bool,
        thumbhash -> Nullable<Bytea>,
        has_variants -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    user_settings (id) {
        id -> Uuid,
        user_id -> Int4,
        theme -> Varchar,
        language -> Varchar,
        notifications_enabled -> Bool,
        privacy_show_program -> Bool,
        privacy_discoverable -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    users (id) {
        id -> Int4,
        pid -> Uuid,
        email -> Varchar,
        password -> Varchar,
        api_key -> Varchar,
        name -> Varchar,
        reset_token -> Nullable<Varchar>,
        reset_sent_at -> Nullable<Timestamptz>,
        email_verification_token -> Nullable<Varchar>,
        email_verification_sent_at -> Nullable<Timestamptz>,
        email_verified_at -> Nullable<Timestamptz>,
        magic_link_token -> Nullable<Varchar>,
        magic_link_expiration -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        is_review_stub -> Bool,
        banned_at -> Nullable<Timestamptz>,
        banned_reason -> Nullable<Text>,
    }
}

diesel::joinable!(conversation_members -> conversations (conversation_id));
diesel::joinable!(conversations -> events (event_id));
diesel::joinable!(messages -> conversations (conversation_id));
diesel::joinable!(messages -> uploads (attachment_upload_id));
diesel::joinable!(message_reactions -> messages (message_id));
diesel::joinable!(chat_message_reveals -> messages (message_id));
diesel::joinable!(chat_message_reveals -> users (viewer_user_id));
diesel::joinable!(chat_message_reports -> messages (message_id));
diesel::joinable!(chat_message_reports -> users (reporter_user_id));
diesel::joinable!(event_attendees -> events (event_id));
diesel::joinable!(event_attendees -> profiles (profile_id));
diesel::joinable!(event_interactions -> events (event_id));
diesel::joinable!(event_interactions -> profiles (profile_id));
diesel::joinable!(event_tags -> events (event_id));
diesel::joinable!(event_tags -> tags (tag_id));
diesel::joinable!(events -> profiles (creator_id));
diesel::joinable!(profile_tags -> profiles (profile_id));
diesel::joinable!(profile_tags -> tags (tag_id));
diesel::joinable!(reports -> profiles (reporter_id));
diesel::joinable!(profiles -> users (user_id));
diesel::joinable!(sessions -> users (user_id));
diesel::joinable!(user_settings -> users (user_id));
diesel::joinable!(xp_scans -> profiles (scanner_id));
diesel::joinable!(task_completions -> profiles (profile_id));

diesel::allow_tables_to_appear_in_same_query!(
    auth_rate_limits,
    chat_message_reports,
    chat_message_reveals,
    conversation_members,
    conversations,
    degrees,
    event_attendees,
    event_interactions,
    event_tags,
    events,
    job_outbox,
    message_reactions,
    messages,
    otp_codes,
    profile_blocks,
    profile_bookmarks,
    profile_tags,
    profiles,
    push_subscriptions,
    reports,
    sessions,
    tags,
    uploads,
    user_settings,
    users,
    task_completions,
    user_audit_log,
    xp_scans,
);
