//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod degrees;
pub mod event_attendees;
pub mod event_tags;
pub mod events;
pub mod matrix_dm_rooms;
pub mod otp_codes;
pub mod profile_tags;
pub mod profiles;
pub mod sessions;
pub mod tags;
pub mod uploads;
pub mod user_settings;
pub mod users;
