//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
pub use super::degrees::Entity as Degrees;
pub use super::event_attendees::Entity as EventAttendees;
pub use super::event_tags::Entity as EventTags;
pub use super::events::Entity as Events;
pub use super::profile_tags::Entity as ProfileTags;
pub use super::profiles::Entity as Profiles;
pub use super::sessions::Entity as Sessions;
pub use super::tags::Entity as Tags;
pub use super::uploads::Entity as Uploads;
pub use super::user_settings::Entity as UserSettings;
pub use super::users::Entity as Users;
